### ISSUE TITLE
USE_1 : Login as employee

### ISSUE THREAD

**Issue by ograton** [SofteamOuest-Opus/user-mgmt#2] opened 2019-06-28 09:36 UTC
(https://github.com/SofteamOuest-Opus/specs/blob/master/user-mgmt/software-design-description.adoc#scenario-s_1)

**Comment by yvzn** [comment] 2019-11-29 11:01
duplicate of #6
duplicate of #7
duplicate of #8

**Comment by yvzn** [comment] 2019-11-29 11:02
duplicate of #6

**Comment by yvzn** [comment] 2019-11-29 11:02
duplicate of #7

**Closed by yvzn** 2019-11-29 11:01 UTC

**Comment by yvzn** [comment] 2019-11-29 11:02
duplicate of #7
