### ISSUE TITLE
USE_3 : Get data of one employee

### ISSUE THREAD

**Issue by ograton** [SofteamOuest-Opus/user-mgmt#4] opened 2019-06-28 09:38 UTC
(https://github.com/SofteamOuest-Opus/specs/blob/master/user-mgmt/software-design-description.adoc#scenario-s_3)

**Comment by yvzn** [comment] 2019-11-29 11:04
duplicate of #10

**Comment by yvzn** [comment] 2019-11-29 11:04
duplicate of #11

**Closed by yvzn** 2019-11-29 11:04 UTC
